### ISSUE TITLE
Idea for enhancement: abilty to toggle/choose between emulation cores for ADLMIDI/OPNMIDI

### ISSUE THREAD

**Issue by papiezak** [WohlSoft/SDL-Mixer-X#12]
Since both ADLMIDI and OPNMIDI support two cores (less acurate but faster DOSbox/Gens and more accutare but resource-hungry Nuked cores) would it be possible to have the option for choosing between them? 
*sorry if it has more to do with audiocodecs rather than mixer library itself*

**Comment by Wohlstand** [comment]
Those features are must be implemented on those libraries http://github.com/Wohlstand/libADLMIDI and http://github.com/Wohlstand/libOPNMIDI are mainstream repositories of those codecs. AudioCodecs is just a collection of codecs are copied from different repositories and combined into united CMake/QMake build project. Any changes on main codecs I applying on original repos and then I coping tested/stable changes into AudioCodecs for final testing as "how it will work in SDL Mixer X".

For now ADLMIDI by default uses Nuked for PC while OPNMIDI uses Gens everywhere (As Nuked OPL3 has acceptable performance to work fine on PCs and Nuked OPN2 is much more heavy which gives inability to simulate more than 3~4 chips on same CPU core without getting of choppy output).

Anyway I have a plan to provide ability to support more than one emulation core with ability to switch it in runtime rather having separate builds for each emulation core.

**Comment by Wohlstand** [comment]
Yes, now both libADLMIDI and libOPNMIDI are now supporting emulator switching and I gonna to bind those options to SDL Mixer X API probably today after job.

**Comment by papiezak** [comment]
looks like emulaton core choice is  possible by editing raw MIDI arguments, so it's done I guess.

**Comment by Wohlstand** [comment]
The con of MIDI raw arguments now is no way to pass custom bank path I wanna to provide...
But yeah, raw MIDI arguments are allowing emulator setup. :fox_face:
