### ISSUE TITLE
Implement support for libXMP codec

### ISSUE THREAD

**Issue by RyanBram** [WohlSoft/SDL-Mixer-X#13]
Libxmp is a library that renders module files to PCM data. It supports
over 90 mainstream and obscure module formats including Protracker (MOD),
Scream Tracker 3 (S3M), Fast Tracker II (XM), and Impulse Tracker (IT).

It is written in C and has 2 license options:
1. LGPL for [full version](https://github.com/cmatsuoka/libxmp), suitable for user who need to play various module format;
2. MIT for [lite version](https://github.com/cmatsuoka/libxmp/tree/master/lite), suitable for user who prefer non copyleft license and doesn't need too many format support.

**Comment by Wohlstand** [comment]
I think, I need to review how it will work as I looking for replacement of libModPlug which produces even good, but too-loud sound and lacks some set of formats, or libMikMod which produces non-clear and in some cases may crash. I checked out libOpenMPT which was a candidate to replace libModPlug, but it seems too heavy (+10 MB binary).

**Comment by RyanBram** [comment]
Great.
Thanks you very much for your response.

**Comment by Wohlstand** [comment]
I see library is able to play IMF (Imago Orpheus) files which ModPlug is not able to play, and I see that size of built static library is ~4 MB and built example application (statically linked XMP and dynamically all other dependencies) has size in ~2MB, it's a good thing!
I'll keep this thread and later I'll try to provide CMake build for XMP and include it into AudioCodecs repo for future adding into SDL Mixer X as alternative to ModPlug and MikMod!

Anyway, cons of XMP I see:
- No native ability to get absolute time position in the song (ModPlug has internally, but wasn't binded into public officially, I modified a library to make that function be public) which will give better positioning support
- No native ability to take a full time length of the song (ModPlug has)

However, that is not a trouble, it will just return -1 as this codec doesn't supports full positioning.
At me I have cases of positioning on MP3 codecs:
- libMAD has no native positioning, but I have implemented it around, therefore MAD-based MP3 playing supports full positioning
- MPG123 has full positioning with few exceptions I have implemented to have full support for positioning
- SMPEG has no way to provide positioning as library itself is clunky and no more supported (for choice of MPG123 as same-license alternative)

**Comment by Wohlstand** [comment]
Just now I have tested it out, and it seems good, and even it's super-simpleness, the positioning is possible to implement by libMAD's way.
The ID3Tag GPL2-licensed library to parse ID3 tags and take the begin position to avoid some crap: I have found that libMAD on some files have produced a damaged sound output and later have crashed. Then I began to use ID3Tag library not for tag parsing, but also for begin position retrieving and I thinking to provide simplified alternative to that.

**Comment by Wohlstand** [comment]
@RyanBram , libXMP has been implemented, and it works, include full seekability support!

**Comment by RyanBram** [comment]
Great. What a great news!

Do you want me to test the feature?
I don't know much about programming and compiling software, so if there is a prebuilt binary that can be tested, I will be happy to try it.

**Comment by Wohlstand** [comment]
> Do you want me to test the feature?

Yes, that would be cool, to let you confirm that everything works as needed.

>  I don't know much about programming and compiling software, so if there is a prebuilt binary that can be tested, I will be happy to try it.

The only question which operating system you are use?
Anyway, there are two ways of support: as a part of AudioCodecs libs set, and as system-wide installed original libXMP.

Anyway, myself I have found a possible issue on ARM (tested on my Android phone): when I playing music via libXMP, then stopping it, the game can freeze which I didn't had before... Possibly a bug of libXMP itself that I need to also test and polish separately.

**Comment by RyanBram** [comment]
Cool.
I have Windows 10 Home system, Lubuntu Bionic Beaver, and an Android One (Pie) Phone with Snapdragon 625 SoC.

For Windows I have tried your  PGE MusPlay, but not the current build, so I am not sure what changes you've made.

**Comment by Wohlstand** [comment]
> PGE MusPlay

You need the most fresh Laboratory bulid taken from here: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/bin-w64/_packed/pge-musplay-master-win64.zip . I have posted libXMP and folks into anywhere include this. libXMP here works by default, also you are able to verify will it work or not by playing IMF files: [IMF Files.zip](https://github.com/WohlSoft/SDL-Mixer-X/files/2957343/IMF.Files.zip). Before libXMP was added, they aren't be playable (the MikMod only was able to play them, but ModPlug that was in use here, can't play them).

For Android you can try out [experimental Android build of my game engine](https://wohlsoft.ru/pgewiki/PGE_Engine:_Installing_preview_Android_version_(2019)) that I have updated recently, with one exception: take [this episode](http://wohlsoft.ru/PGE/_downloads/noarch/episodes/The%20Invasion%20-%20customized.7z) which contains many tracker music that will affect libXMP working.

**Comment by Wohlstand** [comment]
On Linux you are easily can build complete PGE toolchain, and the complete manual is provided here: https://wohlsoft.ru/pgewiki/Building_PGE_From_sources

**Comment by RyanBram** [comment]
Hi @Wohlstand .
I am really sorry for taking very looooonngg time to reply you.
I have tested the IMF Files under windows. Most of them is played well in your player, except one: spaceintro.imf .
I will report you again after testing for Android.

**Comment by RyanBram** [comment]
I also use pre-compiled XMP binary I got from [here](http://www.un4seen.com/)  and it also failed to play spaceintro.imf.
So the problem must be in XMP itself. 
[libxmp 4.4.1 Adlib.zip](https://github.com/WohlSoft/SDL-Mixer-X/files/3359266/libxmp.4.4.1.Adlib.zip)

**Comment by Wohlstand** [comment]
Done! https://github.com/cmatsuoka/libxmp/issues/142

**Comment by Wohlstand** [comment]
@RyanBram, good news: @sezero have found a solution for this issue and I have applied it! :fox_face: 
I tested it on my end, and it now works!

**Comment by Wohlstand** [comment]
Okay, I don't think this should be kept opened, the thing works and completed now.
