### ISSUE TITLE
Implement Multi-Music API

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/SDL-Mixer-X#2]
This API will allow playing multiple parallel sound streams without loading the entire sound into memory. This will allow the creation of a complex sound atmosphere, cross-fade of two kinds of music, etc.

* -[x] Provide alternative music functions to those are lack the `Mix_Music` pointer argument and deprecate old.
* -[x] Add into the mixer stream the array of playing multi-musics
* -[x] Provide public API to manage to play multi-music streams
* -[x] Add music individual effect hooks
* -[x] Implement effects API to allow the panning and position effects to be applied in the same way as Chunks
* -[x] Make music individual effects work also for old music API
* -[x] Document all new-added calls

**Comment by Wohlstand** [comment]
@sezero, hello!
In the past week, I started to implement the actual multi-music thing, right now going on the "wip-multi-music" branch. At the current moment, it fully works except for effects (I do plan to add the same effects API as for chunks, but every individual music stream).

The thing has been implemented to be an additional API that fully replaces the old existing, the old API will behave the same as before my update. All new functions with the "Stream" suffix work for the multi-music API, and that allows parallel work of multiple Mix_Music instances.

Possible issues: some codec libraries or things don't allow multiple music instances (for example, Native MIDI, also, possibly, MikMod won't allow multiple parallel songs, Timidity allows multiple songs, but doesn't allow using different patchsets per song).
So, at the code I had to forbid use the Native MIDI with the MultiMusic API, keeping this ability being used with the old music API. Probably I can allow these libraries to work with MultiMusic API, but I will prevent re-using the same library more times than one to avoid these issues related to codecs that can't run parallel copies at all.

Can you quickly review some and give some points on this and/or some suggestions?

p.s. simply compare "master" and "wip-multi-music" branches to see what I actually made

**Comment by sezero** [comment]
Had a _really_ brief look, changes _look_ sane, although it doesn't compare
to mainstream SDL_mixer which I actually wanted to do. So, if you generate
a patch against mainstream, I can probably more useful.

Some pedantry: Don't leave parameters as `()` but explicitly use `(void)`,
e.g. in header: `Mix_GetVolumeMusicGeneral()`, `Mix_PauseMusicStreamAll()`,
`Mix_ResumeMusicStreamAll()`. Also their definitions in actual sources,
e.g. in music.c: `_Mix_MultiMusic_CloseAndFree()`, `_Mix_MultiMusic_HaltAll()`,
`_Mix_MultiMusic_PauseAll()`, `_Mix_MultiMusic_ResumeAll()`,
`Mix_PauseMusicStreamAll()`, `Mix_ResumeMusicStreamAll()`.  there may be more.

`music_mix_stream()`: does it have to be `inline`?

> Native MIDI, also, possibly, MikMod won't allow multiple parallel songs,

Correct, neither of them does,

> Timidity allows multiple songs,

Correct.

> ... but doesn't allow using different patchsets per song.

Ugh, isn't that stretching it too far?

**Comment by Wohlstand** [comment]
> Don't leave parameters as () but explicitly use (void),

Will fix

> music_mix_stream(): does it have to be inline?

It's the method used to process each music stream, I made it as a separated call rather than writing it inside the `multi_music_mixer()`

> Ugh, isn't that stretching it too far?

At me, there is already implemented the projection to don't reload the Timidity's patchset when any song(s) were loaded. At me, the ability to replace the Timidity patchset on the fly has been implemented a while ago. I do use this in my experiments and provide an ability to choose between multiple patch sets. I do also have some custom patchsets. However, since I implemented the separated support FluidLite with my own MIDI sequencer (that has loops support), this thing for Timidity is not so important, rather to just replace patchset without player's and/or libary restart.

**Comment by Wohlstand** [comment]
> So, if you generate a patch against mainstream, I can probably more useful.

I'll do it once I will polish the thing here and it will work stable and as intended, right now there is the development stage is, therefore a thing appears at the feature branch rather on the top of master.

**Comment by Wohlstand** [comment]
Just now I added built-in effects work with music too: position, distance, reverse stereo, panning.
Now I will need to tune the code if needed, and document all new-added features.

**Comment by Wohlstand** [comment]
One thing I can add - allow old music API use effects too, that's quite simple to add

**Comment by Wohlstand** [comment]
Done, old music API now also supports music individual effects.

**Comment by Wohlstand** [comment]
Just now, I completed documenting all new-added functions.

**Comment by rversteegen** [comment]
Thank you hugely for this! I've spent the last 15 years of my life doing little else but hating SDL_Mixer for all the features it's missing and all its bugs, but it's gotten so much better, and now with this it looks like I'll have to find something else to hate. So many of my users over the years have asked for crossfading music!

**Comment by Wohlstand** [comment]
@rversteegen, I'm glad to hear these nice words! Thank you for the support!

**Comment by rversteegen** [comment]
All the other features of SDL Mixer X are really great too!

**Comment by Wohlstand** [comment]
Btw, one little note: All old music functions will still work as-is to keep the backward compatibility with the old behavior. The new API calls with `*Stream` suffix was been added:
```
Mix_PlayMusicStream
Mix_FadeInMusicStream
Mix_FadeInMusicStreamPos
etc.
```
Unlike their elder variants, all these calls receive the `Mix_Music*` argument you can control individually and run in parallel as you want.

Also, please report any bugs you'll find while testing this thing in action. I had to polish it and on my end seems it works stable, however, if I missed up something, I'll be glad to fix that.
