### ISSUE TITLE
Implement public API for music tempo changing

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/SDL-Mixer-X#22]
Some music formats (and their playing libraries and codecs) are supports tempo changing on the fly: MIDI (via libADLMIDI and libOPNMIDI), Game music emulators, and tracker musics. It's would be nice to have an ability to change the tempo of given music.

**Comment by Alucard648** [comment]
https://github.com/WohlSoft/PGE-Project/issues/163 Flag 2.

**Comment by Wohlstand** [comment]
Made!
