### ISSUE TITLE
CMake macro to force disable/enable module that doesn't comply with ZLib

### ISSUE THREAD

**Issue by knight-ryu12** [WohlSoft/SDL-Mixer-X#39]
refer to #38, it'd be much easier to get it going.

**Comment by Wohlstand** [comment]
Done!

**Comment by knight-ryu12** [comment]
I'd say return error whenever license conflict occurs.

**Comment by Wohlstand** [comment]
> I'd say return error whenever license conflict occurs.
That just adds a headache to let users guess what they should disable to resolve the conflict, etc.

**Comment by Wohlstand** [comment]
Anyway, the thing is done, if needed, can be improved later
