### ISSUE TITLE
Add support for PMD .M/.M2 format

### ISSUE THREAD

**Issue by freq-mod** [WohlSoft/SDL-Mixer-X#44]
Regarding popular formats that can be supported here, I can recommend PMD's .M/.M2/MZ songs.

These are compiled MML sequences for PC-9801 computers, targetting YM2203 and YM2608, together with PC-9801-86 PCM sound, providing extra 8 channels for use with YM2608 and ability to play PCM samples through PSG.

**Comment by Wohlstand** [comment]
That would go into the libOPNMIDI side as this library is the main backend that supports anything related to OPN* chip family. That would be the same as Id's IMF supported through the libADLMIDI.

**Comment by freq-mod** [comment]
Well, .M(x) differs from .MIDI (although there are converters out there), but if it's on libOPNMIDI, I can open the issue ticket on that repo
