### ISSUE TITLE
MIDI Auto Arpeggio Setter

### ISSUE THREAD

**Issue by red436** [WohlSoft/SDL-Mixer-X#52]
line 3364 of src/music.c should be
`(void)aa_en;`
not
`(void)frb;`

Thank's for the great work!

**Comment by Wohlstand** [comment]
Whoops, nice catch! :)
Some weeks ago I had fixed a similar build error when the libOPNMIDI build has been disabled.

**Comment by Wohlstand** [comment]
Fixed just now! :+1:
