### ISSUE TITLE
Disable GPL components by default

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/SDL-Mixer-X#53]
As an addition to #39, to simplify the future use of the library, take the way of the FFMPEG project: by default, the configure script produces the LGPL v2.1+ code. However, configuring the script allows enables some GPL modules, and in some cases it allows enabling non-free modules, causing the library's license to be "non-free, non-redistributable". In all cases, users have to explicitly enable support for modules with viral GPL or non-free licenses. This should avoid any unexpected cases when GPL modules got used with non-free projects, or LGPL modules got statically linked into GPL-incompatible projects.

**Comment by 0lhi** [comment]
I approve the idea of disabling GPL components by default.

That's the first I hear about non-free modules though... are they already included, or planned be included?

I hope not 😟

**Comment by Wohlstand** [comment]
> That's the first I hear about non-free modules though... are they already included, or planned be included?

No non-free modules here, I mentioned them because they were at the FFMPEG side presented and may be enabled optionally. As I mentioned FFMPEG's modules enabling strategy as an example.

**Comment by Wohlstand** [comment]
Okay, since this moment, library disables all LGPL/GPL libraries by default, and enables them if they enabled explicitly.
