### ISSUE TITLE
[BUG] Window freezes when playing via Native MIDI

### ISSUE THREAD

**Issue by LoveBodhi** [WohlSoft/SDL-Mixer-X#57]
I used MusPlay for example:

1. Setup → MIDI Setup
2. Choose "Native MIDI" in the list of "MIDI Device"
3. Open a MIDI file
4. Window freezes

PS: Tested via **Windows 10** and **Virtual MIDI Synth**

**Comment by jadasse** [comment]
I'm having this issue

**Comment by Wohlstand** [comment]
I fixed this recently, forgot to close this.
