### ISSUE TITLE
Cannot build `pxtone` due to invalid character when system codepage is 936

### ISSUE THREAD

**Issue by defisym** [WohlSoft/SDL-Mixer-X#70]
Builder will return error message about `SDL-Mixer-X\src\codecs\pxtone\pxtnEvelist.cpp` and `SDL-Mixer-X\src\codecs\pxtone\pxtnMaster.cpp`, saying `rrr` is not the member of `_x4x_EVENTSTRUCT` or `_x4x_MASTER`, but actually it's defined.
According to the warning of visual studio, it seems due to the invalid character.

![image](https://github.com/WohlSoft/SDL-Mixer-X/assets/55148235/febfa218-1fb7-426a-9ea5-d73b7e55b049)
Translation: 
yellow: this file includes characters can't display in codepage (936), please save it to Unicode to avoid data losing
red:  `rrr`: is not the member of `_x4x_EVENTSTRUCT`

Resave both file to UTF-8 Bom can fix this build error. This may specific to my enviourment, language in codepage 936 and build with visual studio, which seems only treat UTF-8 with Bom as actual Unicode file.

**Comment by Wohlstand** [comment]
Huh, good catch. I'll fix that. Anyway, origian charset of these files was Shift-JIS, and I was sure that I converted all of them into UTF-8, I'll fix this as fast as possible.

**Comment by Wohlstand** [comment]
Anyway, what MSVC version you do have? On my end, it builds with many different versions of MSVC normally :thinking:

**Comment by Wohlstand** [comment]
I guess, the fix would be an adding of the kind of `/utf8` flag to the compiler (at CMake setup) to eliminate this issue. I'll try some on my end, and I'll let you know when I'll implement this.

**Comment by defisym** [comment]
Thanks for the quick reply! 

> I was sure that I converted all of them into UTF-8
Yes, I can confirm this, but msvc still not build it until I resave both file to UTF-8 BOM, which is the default format when save as unicode in visual studio. 

> what MSVC version you do have?
2022 community, latest update, 17. 5.X IIRC. 

> On my end, it builds with many different versions of MSVC normally
Then it must by the language difference: some character has no issue in your language but will affect the build on my side. 

> I guess, the fix would be an adding of the kind of /utf8 flag to the compiler
I'm not familiar with cmake, if this flag can force compiler to work in unicode mode instead of auto detect file encoding format, then it should work.

**Comment by Wohlstand** [comment]
Recently I sent a fix to CMake build, so it adds /utf-8 argument and it should work just fine. Please verify the thing. Project needs to be re-generated after CMake side update.

**Comment by defisym** [comment]
![image](https://github.com/WohlSoft/SDL-Mixer-X/assets/55148235/a78f8424-f556-4ee9-a3d4-5e0a9dd4da57)

Thanks, I can confirm it can pass the build without any modifications.
