### ISSUE TITLE
Do you have a library that allows you to drive a bunch of different soft synths directly?

### ISSUE THREAD

**Issue by nikitalita** [WohlSoft/SDL-Mixer-X#80]
I need to drive a bunch of selectable software synths (and ideally, midi ports) directly from my own sequencer; Mixer doesn't allow you to do that, but I was curious if you knew of anything that was like that.

**Comment by Wohlstand** [comment]
Hello! Do you wanted to unite different MIDI synthesizer libraries and map MIDI events between them? If you making a kind of MIDI player or even Editor, then you better to use these MIDI libraries and hardware interfaces directly. The thing shouldn't be hard to implement: MIDI out API is pretty simple in various OSes if you want to send real-time MIDI commands, and all you need to make is the receiver function, the mapping array (channels, tracks, or drum notes) to forward between different ports. What about software synthesizer libraries, you will need to implement suitable overlays over them to use their real-time MIDI functions and run the PCM output, mix it and send to audio output.

**Comment by Wohlstand** [comment]
@nikitalita, could you explain details of what do you actually want to have?

**Comment by Wohlstand** [comment]
Whoops, just now I found this is a duplicate for #68. If you want to append something, please go to related issue.
